package com.hwl.beta.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hwl.beta.db.entity.ChatRecordMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAT_RECORD_MESSAGE".
*/
public class ChatRecordMessageDao extends AbstractDao<ChatRecordMessage, Long> {

    public static final String TABLENAME = "CHAT_RECORD_MESSAGE";

    /**
     * Properties of entity ChatRecordMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property RecordId = new Property(0, Long.class, "recordId", true, "_id");
        public final static Property RecordType = new Property(1, int.class, "recordType", false, "RECORD_TYPE");
        public final static Property RecordImage = new Property(2, String.class, "recordImage", false, "RECORD_IMAGE");
        public final static Property FromUserId = new Property(3, long.class, "fromUserId", false, "FROM_USER_ID");
        public final static Property FromUserName = new Property(4, String.class, "fromUserName", false, "FROM_USER_NAME");
        public final static Property FromUserHeadImage = new Property(5, String.class, "fromUserHeadImage", false, "FROM_USER_HEAD_IMAGE");
        public final static Property ToUserId = new Property(6, long.class, "toUserId", false, "TO_USER_ID");
        public final static Property ToUserName = new Property(7, String.class, "toUserName", false, "TO_USER_NAME");
        public final static Property ToUserHeadImage = new Property(8, String.class, "toUserHeadImage", false, "TO_USER_HEAD_IMAGE");
        public final static Property GruopGuid = new Property(9, String.class, "gruopGuid", false, "GRUOP_GUID");
        public final static Property GroupName = new Property(10, String.class, "groupName", false, "GROUP_NAME");
        public final static Property Title = new Property(11, String.class, "title", false, "TITLE");
        public final static Property ContentType = new Property(12, int.class, "contentType", false, "CONTENT_TYPE");
        public final static Property Content = new Property(13, String.class, "content", false, "CONTENT");
        public final static Property UnreadCount = new Property(14, int.class, "unreadCount", false, "UNREAD_COUNT");
        public final static Property SendTime = new Property(15, java.util.Date.class, "sendTime", false, "SEND_TIME");
    }


    public ChatRecordMessageDao(DaoConfig config) {
        super(config);
    }
    
    public ChatRecordMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAT_RECORD_MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: recordId
                "\"RECORD_TYPE\" INTEGER NOT NULL ," + // 1: recordType
                "\"RECORD_IMAGE\" TEXT," + // 2: recordImage
                "\"FROM_USER_ID\" INTEGER NOT NULL ," + // 3: fromUserId
                "\"FROM_USER_NAME\" TEXT," + // 4: fromUserName
                "\"FROM_USER_HEAD_IMAGE\" TEXT," + // 5: fromUserHeadImage
                "\"TO_USER_ID\" INTEGER NOT NULL ," + // 6: toUserId
                "\"TO_USER_NAME\" TEXT," + // 7: toUserName
                "\"TO_USER_HEAD_IMAGE\" TEXT," + // 8: toUserHeadImage
                "\"GRUOP_GUID\" TEXT," + // 9: gruopGuid
                "\"GROUP_NAME\" TEXT," + // 10: groupName
                "\"TITLE\" TEXT," + // 11: title
                "\"CONTENT_TYPE\" INTEGER NOT NULL ," + // 12: contentType
                "\"CONTENT\" TEXT," + // 13: content
                "\"UNREAD_COUNT\" INTEGER NOT NULL ," + // 14: unreadCount
                "\"SEND_TIME\" INTEGER);"); // 15: sendTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAT_RECORD_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChatRecordMessage entity) {
        stmt.clearBindings();
 
        Long recordId = entity.getRecordId();
        if (recordId != null) {
            stmt.bindLong(1, recordId);
        }
        stmt.bindLong(2, entity.getRecordType());
 
        String recordImage = entity.getRecordImage();
        if (recordImage != null) {
            stmt.bindString(3, recordImage);
        }
        stmt.bindLong(4, entity.getFromUserId());
 
        String fromUserName = entity.getFromUserName();
        if (fromUserName != null) {
            stmt.bindString(5, fromUserName);
        }
 
        String fromUserHeadImage = entity.getFromUserHeadImage();
        if (fromUserHeadImage != null) {
            stmt.bindString(6, fromUserHeadImage);
        }
        stmt.bindLong(7, entity.getToUserId());
 
        String toUserName = entity.getToUserName();
        if (toUserName != null) {
            stmt.bindString(8, toUserName);
        }
 
        String toUserHeadImage = entity.getToUserHeadImage();
        if (toUserHeadImage != null) {
            stmt.bindString(9, toUserHeadImage);
        }
 
        String gruopGuid = entity.getGruopGuid();
        if (gruopGuid != null) {
            stmt.bindString(10, gruopGuid);
        }
 
        String groupName = entity.getGroupName();
        if (groupName != null) {
            stmt.bindString(11, groupName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(12, title);
        }
        stmt.bindLong(13, entity.getContentType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(14, content);
        }
        stmt.bindLong(15, entity.getUnreadCount());
 
        java.util.Date sendTime = entity.getSendTime();
        if (sendTime != null) {
            stmt.bindLong(16, sendTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChatRecordMessage entity) {
        stmt.clearBindings();
 
        Long recordId = entity.getRecordId();
        if (recordId != null) {
            stmt.bindLong(1, recordId);
        }
        stmt.bindLong(2, entity.getRecordType());
 
        String recordImage = entity.getRecordImage();
        if (recordImage != null) {
            stmt.bindString(3, recordImage);
        }
        stmt.bindLong(4, entity.getFromUserId());
 
        String fromUserName = entity.getFromUserName();
        if (fromUserName != null) {
            stmt.bindString(5, fromUserName);
        }
 
        String fromUserHeadImage = entity.getFromUserHeadImage();
        if (fromUserHeadImage != null) {
            stmt.bindString(6, fromUserHeadImage);
        }
        stmt.bindLong(7, entity.getToUserId());
 
        String toUserName = entity.getToUserName();
        if (toUserName != null) {
            stmt.bindString(8, toUserName);
        }
 
        String toUserHeadImage = entity.getToUserHeadImage();
        if (toUserHeadImage != null) {
            stmt.bindString(9, toUserHeadImage);
        }
 
        String gruopGuid = entity.getGruopGuid();
        if (gruopGuid != null) {
            stmt.bindString(10, gruopGuid);
        }
 
        String groupName = entity.getGroupName();
        if (groupName != null) {
            stmt.bindString(11, groupName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(12, title);
        }
        stmt.bindLong(13, entity.getContentType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(14, content);
        }
        stmt.bindLong(15, entity.getUnreadCount());
 
        java.util.Date sendTime = entity.getSendTime();
        if (sendTime != null) {
            stmt.bindLong(16, sendTime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChatRecordMessage readEntity(Cursor cursor, int offset) {
        ChatRecordMessage entity = new ChatRecordMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // recordId
            cursor.getInt(offset + 1), // recordType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // recordImage
            cursor.getLong(offset + 3), // fromUserId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // fromUserName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fromUserHeadImage
            cursor.getLong(offset + 6), // toUserId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // toUserName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // toUserHeadImage
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // gruopGuid
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // groupName
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // title
            cursor.getInt(offset + 12), // contentType
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // content
            cursor.getInt(offset + 14), // unreadCount
            cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)) // sendTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChatRecordMessage entity, int offset) {
        entity.setRecordId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecordType(cursor.getInt(offset + 1));
        entity.setRecordImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFromUserId(cursor.getLong(offset + 3));
        entity.setFromUserName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFromUserHeadImage(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setToUserId(cursor.getLong(offset + 6));
        entity.setToUserName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setToUserHeadImage(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setGruopGuid(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setGroupName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTitle(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setContentType(cursor.getInt(offset + 12));
        entity.setContent(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setUnreadCount(cursor.getInt(offset + 14));
        entity.setSendTime(cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChatRecordMessage entity, long rowId) {
        entity.setRecordId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChatRecordMessage entity) {
        if(entity != null) {
            return entity.getRecordId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChatRecordMessage entity) {
        return entity.getRecordId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
